version: '2'

services:

  server:
    build:
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/var/lib/postgresql/data
    env_file:
      - .env